---
########## FirewallD Setup  ##########
- name: Remove UFW is removed on Debian systems.
  ansible.builtin.package:
    name: ufw
    state: absent
  when: ansible_os_family == "Debian"

- name: Install Pre-Req python3-firewall is installed on Debian systems.
  ansible.builtin.package:
    name:
      - python3-firewall
    state: latest
  when: ansible_os_family == "Debian"


- name: Ensure firewalld is installed and running.
  ansible.builtin.package:
    name: firewalld
    state: latest

- name: Configure FirewallD Open Ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: false
    offline: true
  loop: "{{ fw_ports }}"
  register: restart_firewalld

- name: Configure FirewallD Open Services
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: false
    offline: true
  loop: "{{ fw_services }}"
  register: restart_firewalld

- name: Enable FirewallD
  ansible.builtin.service:
    name: firewalld
    enabled: yes

- name: Restart FirewallD With Changes
  ansible.builtin.service:
    name: firewalld
    state: restarted
  when:
    - restart_firewalld is changed